### ISSUE TITLE
Unable to Resize Maps

### ISSUE THREAD

**Issue by DustBird** [TheGamerASD/AWBW-Design-Maps-Improved#1]
I've attempted to resize maps, as well as a friend of mine on a different account, and nothing has happened. All other features of the extension have been working as normal. The map resize feature makes the pop-up with the dropdowns asking for user input on whether to shrink or expand, and by how many tiles, but there is no map resizing occurring after hitting the "Resize" button and then "OK" in the following pop-up.

**Comment by RealMVC** [comment]
The new version (1.3.2) should fix this issue, let me know if there are any other issues.
